### ISSUE TITLE
Option to reverse comment replies' order

### ISSUE THREAD

**Issue by Ilethas** [sameerdash2/comment-viewer#11]
Currently when you click to view replies to a comment, the last one is the first reply (chronologically). Would it be possible to make an option to reverse the order, so that when you view the replies, the first one you see is the first one that was published? I find this app much better for browsing comments than youtube itself, so I thought it wouldn't hurt to ask 😀

**Comment by sameerdash2** [comment]
Fixed now. i also added a check in case the API folks reverse the order again; it should still display in time-ascending order. 🤞

_Technical details for those interested_:

Receiving replies from the API in correct order now reveals a possible optimization. Previously, we had to fetch _all_ of a comment's replies just to get to the first one, since they arrived in reverse order. For a comment with the maximum 500 replies, this took 5 API requests (about 2.5 seconds). But now that the first batch of 100 replies includes the first reply, we could just immediately display the first 100 (cutting the delay down to ~0.6 seconds). Sounds great, but this also necessitates a bunch of extra HTML and buttons to paginate the replies, and maybe I would've attempted it back in 2020 when I worked on this all day but now a 2.5 second delay is nothing to fret about. Plus, displaying all 500 replies in one click is something you can't do on the watch page 🙃
