### ISSUE TITLE
passing video id/url as a parameter to the comment-viewer

### ISSUE THREAD

**Issue by khlsvr** [sameerdash2/comment-viewer#5]
To be able to open the comment-viewer with a given youtube video directly this would be useful.

For example if I want to have a script that takes a youtube URL as a parameter and it would open the URL in a video player for example mpv and then also open the  comments of that youtube video separately in comment-viewer.

**Comment by sameerdash2** [comment]
Implemented. You can supply video IDs with the `v=` parameter. Thanks for the suggestion!

Note that the user still has to manually click "Load all comments" once the page is loaded. I'm hesitant to let the comments start fetching right from page load, since that would make it really easy for someone to write a script & flood the site with 10,000 video requests.

**Comment by khlsvr** [comment]
Thanks for the fast implementation!

**Comment by RingtailRaider** [comment]
Would it be possible to allow for direct links to youtube comments in the url as well (that do load since it's just one comment maybe)? I'm mostly interested for archival reasons, since the internet archive refuses to save comments on videos even when saving a direct link to the comment.

**Comment by sameerdash2** [comment]
@RingtailRaider you can already input direct links to comments, since the `v=`  value gets parsed just like any text entered into the input box. The hard part is first encoding the comment link as a URL. For example, here's a link to a youtube comment:
```
https://www.youtube.com/watch?v=ZYATta5yGtQ&lc=UgyNAzDxQduawT2Bp2B4AaABAg
```
Once encoded (using a tool like https://meyerweb.com/eric/tools/dencoder/), this would be the resulting link to commentviewer:
```
https://commentviewer.com/?v=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DZYATta5yGtQ%26lc%3DUgyNAzDxQduawT2Bp2B4AaABAg
```

To make it simpler, you can submit only the comment ID part -- the code looks for "`lc=`" to spot linked comments.
```
https://commentviewer.com/?v=lc%3DUgyNAzDxQduawT2Bp2B4AaABAg
```
That being said, I tried saving this link ^ in the wayback machine and it doesn't seem to wait long enough for the video/comment to load. 😞  Probably because of the structure of the app (the page first loads empty, and then sends the ID query).
